name: guilt_flutter
description: an app for manage guilt

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get_it: ^7.2.0
  collection: ^1.16.0
  flutter_svg: ^1.1.1+1
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  dartz: ^0.10.1
  freezed: ^2.0.3+1
  shimmer: ^2.0.0
  shimmer_animation: ^2.1.0+1
  freezed_annotation: ^2.0.3
  flutter_keyboard_visibility: ^5.1.1
  logger: ^1.1.0
  qlevar_router: ^1.6.2
  pull_to_refresh: ^2.0.0
  http: ^0.13.4
  package_info_plus: ^1.4.2
  url_launcher: ^6.0.18
  in_app_update: ^3.0.0
  get_storage: ^2.0.3
  connectivity_plus: ^2.3.3
  share_plus: ^4.0.7
  auto_size_text: ^3.0.0
  device_info_plus: ^3.2.4
  shamsi_date: ^1.0.1
  lottie: ^1.3.0
  flutter_native_splash: ^2.2.3
  flutter_markdown: ^0.6.10+2
  expandable: ^5.0.1
  image_picker: ^0.8.5+3
  flutter_spinkit: ^5.1.0
  persian_datetime_picker: ^2.5.0
  dio: ^4.0.6
  sms_user_consent: ^0.1.0
  persian_utils: ^2.0.1
  flutter_staggered_animations: ^1.0.0
  mapir_raster: ^0.0.1
  flutter_map: ^0.14.0
  geolocator: ^9.0.1
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  auto_route_generator: ^4.0.0
  build_runner:
  flutter_launcher_icons: ^0.10.0
  change_app_package_name: ^1.1.0
  rename: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - images/
    - jsons/
  fonts:
    - family: vazir
      fonts:
        - asset: fonts/vazir_bold.ttf
          weight: 700
        - asset: fonts/vazir_medium.ttf
          weight: 600
        - asset: fonts/vazir.ttf
          weight: 500
        - asset: fonts/vazir_light.ttf
          weight: 300
